### PR TITLE
simplify build

### PR DESCRIPTION
**Pull request by pepyakin**
Remove build.rs for just a standard relative path include.

build scripts are an advanced feature. It just happened that this
particular crate did not play nice with a non-cargo build system.

Likely it would be possible to fix it locally, but I actually don't
see any reason for this crate to have a build.rs

I checked it locally and it seems to produce exactly the same results.

LMK if I am missing something.

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
I think it was needed to find the README for `cargo publish` since that builds the crate on its own outside of the workspace.  
Anyway, its probably better to write a small `publish.sh` that shuffles the files prio to publishing than using a `build.rs` - i dont like it either 😆

**Comment by ggwpez** [comment]
Thanks Sergei!

**Comment by pepyakin** [comment]
Do you mind making a release? Would be really helpful!

**Comment by pepyakin** [comment]
Oh sorry, I missed your message above. I wonder if a symbolic link would help.

Check out #14 . GH renders it as a file but it's actually a symbolic link (created by ln -s). It seems that the file is packaged properly, but I also saw your other changes now and they also make sense.

**Pull request merged**
